name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install depot_tools
        run: |
          sudo apt-get install git curl xz-utils python3-pkg-resources python3-virtualenv python3-oauth2client
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "PATH=$(pwd)/depot_tools:$PATH" >> $GITHUB_ENV
          cd depot_tools
          git reset --hard 138bff28
      - name: Build chii
        run: |
          export DEPOT_TOOLS_UPDATE=0
          npm i -g @liriliri/lsla
          npm i
          npm run init:front_end
          npm run build
      - name: Publish package on NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
